 string laptop;
    string speker;
    string phone;
    string watch;
    string ear;
    string charger;
    string ms;
    string msh;
    string bag;
    string ws;
    string wd;
    string ks;
    string car;
    string plane;
    string gun;
    string spin;
    string cube;
    string puzzle;
    string makeup;
    string mg;
    string frag;
    string shamp;
    string creme;
    string oil;
    string fball;
    string bat;
    string bball;
    string cycle;
    string bg;
    string stump;
    string rl;
    string ac;
    string pl;
    string et;
    string hc1;
    string hc2;
    laptop="CORE I3 LAPTOP";
     speker="INTEX IT 2616 SPEKER";
     phone="SMART PHONE";
     watch="SMART WATCH";
     ear="BLUTOOTH EARPHONES";
     charger="CHARGER";
     ms="MEN'SHOES";
     msh="MEN'S SHIRT";
     bag="BAGS";
     ws="WOMEN'S SHOES";
     wd="WOMEN'S DRESS";
     ks="KID'S CLOTHING";
     car="CAR";
     plane="PLANE";
     gun="GUN";
     spin="SPINNER";
     cube="CUBE";
     puzzle="PUZZLE";
     makeup="MAKEUP";
     mg="MEN'S GROOMING";
     frag="FRAGRENCES";
     shamp="SHAMPOO";
     creme="CREME";
     oil="OIL";
     fball="FOOTBALL";
     bat="CRICKET BAT";
     bball="BASKET BALL";
     cycle="CYCLE";
     bg="BADMINTON GEAR";
     stump="STUMP";
     rl="ROBERT LAFORE";
     ac="ANSCI C";
     pl="PYTHON LEARNING";
     et="EXPERIMENTS OF TRUTH";
     hc1="H.C.VERMA 1";
     hc2="H.C.VERMA 2";
     int laptop1;
    int speker1;
    int phone1;
    int watch1;
    int ear1;
    int charger1;
    int ms1;
    int msh1;
    int bag1;
    int ws1;
    int wd1;
    int ks1;
    int car1;
    int plane1;
    int gun1;
    int spin1;
    int cube1;
    int puzzle1;
    int makeup1;
    int mg1;
    int frag1;
    int shamp1;
    int creme1;
    int oil1;
    int fball1;
    int bat1;
    int bball1;
    int cycle1;
    int bg1;
    int stump1;
    int rl1;
    int ac1;
    int pl1;
    int et1;
    int hc11;
    int hc21;
    laptop1=25490;
     speker1=5000;
     phone1=10000;
     watch1=2500;
     ear1=3000;
     charger1=500;
     ms1=2000;
     msh1=1000;
     bag1=1200;
     ws1=1200;
     wd1=500;
     ks1=2300;
     car1=500;
     plane1=800;
     gun1=200;
     spin1=100;
     cube1=250;
     puzzle1=300;
     makeup1=500;
     mg1=200;
     frag1=250;
     shamp1=450;
     creme1=150;
     oil1=100;
     fball1=350;
     bat1=1900;
     bball1=450;
     cycle1=9000;
     bg1=1299;
     stump1=800;
     rl1=400;
     ac1=500;
     pl1=890;
     et1=500;
     hc11=250;
     hc21=250;
